//tealium universal tag - utag.2049 ut4.0.202410241053, Copyright 2024 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;if(utag.ut===undefined){utag.ut={};}
if(utag.ut.loader===undefined){u.loader=function(o){var b,c,l,a=document;if(o.type==="iframe"){b=a.createElement("iframe");o.attrs=o.attrs||{"height":"1","width":"1","style":"display:none"};for(l in utag.loader.GV(o.attrs)){b.setAttribute(l,o.attrs[l]);}b.setAttribute("src",o.src);}else if(o.type=="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";for(l in utag.loader.GV(o.attrs)){b[l]=o.attrs[l];}b.src=o.src;}if(o.id){b.id=o.id;}if(typeof o.cb=="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb();},false);}else{b.onreadystatechange=function(){if(this.readyState=='complete'||this.readyState=='loaded'){this.onreadystatechange=null;o.cb();}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l=="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b);}}};}else{u.loader=utag.ut.loader;}
u.ev={view:1,link:1};u.initialized=false;u.map={};u.extend=[];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f,i;u.data={};for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
if(!window.smartBannerInitialized){!(function(e,n,t,a,o,s,r,i,c){var d=o+"_q";(e[o]=e[o]||{}),(e[d]=e[d]||[]);for(var u=0;u<s.length;u++)r(e[o],e[d],s[u]);(i=n.createElement(t)),(c=n.getElementsByTagName(t)[0]),(i.async=!0),(i.src="https://cdn.adjust.com/adjust-smart-banner-latest.min.js"),(i.onload=function(){e[o]=e[o].default;for(var n=0;n<e[d].length;n++)
e[o][e[d][n][0]]?e[o][e[d][n][0]].apply(e[o],e[d][n][1]):console.error("No such function found in "+o+": "+e[d][n][0]);e[d]=[];window.smartBannerInitialized=true;}),c.parentNode.insertBefore(i,c);})(window,document,"script",0,"AdjustSmartBanner",["init","show","hide","setLanguage","setIosDeepLinkPath","setAndroidDeepLinkPath","setContext","setAndroidAppSchema","setDeepLinkPath",],function(e,n,t){e[t]=function(){n.push([t,arguments]);};});console.log('Initialize AdjustSmartBanner');var style=document.createElement('style');style.innerHTML=`.smart-banner{position:fixed;top:0;z-index:9999;width:100%;}
.smart-banner div{max-width:none!important;}
`;document.head.appendChild(style);const element=document.createElement("div");element.id="smart-banner-container";element.className="smart-banner";document.body.appendChild(element);AdjustSmartBanner.init({appToken:{ios:'tlzzzsn7ra6v',android:'bjjv8labj4p6'},bannerParent:element,onCreated:()=>console.log('Smart banner shown'),onDismissed:()=>console.log('Smart banner dismissed')});}else{console.log('Smart Banner SDK is already initialized.');}
}};utag.o[loader].loader.LOAD(id);})("2049","immobilienscout.is24");}catch(error){utag.DB(error);}
